version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: youapp

  mongo_db_test:
    image: mongo:latest
    container_name: mongo_db_test
    restart: on-failure
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: youapp
